# Bitflow services
bitflow-bitcoin-node:
  container_name: bitcoin-node.bitflow.bfl
  image: 'daedalus2718/bitflow-bitcoin-node:latest'
  ports:
    - "8333:8333"
    - "8332:8332"
    - "5101:5101"
  environment:
    JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5101
  volumes:
    - ../bitflow-bitcoin-node/var/conf/bitflow-bitcoin-node.yml:/opt/bitflow/services/bitflow-bitcoin-node/var/conf/bitflow-bitcoin-node.yml
    - /opt/bitflow
    - /data

bitflow-blockchain:
  container_name: blockchain.bitflow.bfl
  image: 'daedalus2718/bitflow-blockchain:latest'
  ports:
    - "8100:8100"
    - "8101:8101"
    - "5103:5103"
  environment:
    JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5103
  volumes:
    - ../bitflow-blockchain/var/conf/bitflow-blockchain.yml:/opt/bitflow/services/bitflow-blockchain/var/conf/bitflow-blockchain.yml
    - /opt/bitflow
    - /data